playerTabFormat: "{player_prefix}{player_nickname}"
joinMessage: "{player_prefix}{player_nickname} &r&6зашёл в лобби!"
joinNotifications: true
chat: "{player_prefix}{player_nickname}{player_suffix}: {player_message}"
globalChat: "[G] {player_prefix}{player_nickname}{player_suffix}: {player_message}"
localChat: "[L] {player_prefix}{player_nickname}{player_suffix}: {player_message}"
ifNoOneHeardTheMessage: "&cВаше сообщение никто не услышал"
globalPrefix: "!"
localRadius: 100
isGlobalEnabled: false
isChatClickable: true
clickableType: 0
clickableValue: "/profile {player_nickname}"
isChatHover: true
hoverMessage: "{player_prefix}{player_nickname}\n§7Уровень: §60"