name: ChatAndTabManager
main: ru.owopeef.chatandtabmanager.Main
version: 1.0
author: owoPeef
website: www.github.com/owoPeef/ChatAndTabManager
permissions:
  chatandtabmanager.join_notify:
    description: Send chat notify when player is join.
    default: op
  chatandtabmanager.smiles_chat:
    description: Change symbols to smiles in chat.
    default: op